### PR TITLE
fix: adding laravel/framework and removing unnecessary dependencies

### PR DESCRIPTION
**Pull request by wandesnet**
You need to run `composer update`

### CODE REVIEW

**Comment by devajmeireles** [comment]
I stumbled upon this PR going through the repository.

Judging by the package name, I feel there is possible confusion I think. "Asaas PHP": is this something for PHP or Laravel? It's okay that Laravel is PHP, but the title in the name can subject the person's understanding to thinking that the package is generic, and not just for Laravel.

The correct thing **in my opinion** would be:

1. The package has a different name. "Asaas for Laravel", for example - where it would make perfect sense to maintain the dependency on the entire framework

2. The package is generic for PHP, not just Laravel - where it would make sense to maintain separate dependencies, rather than the complete framework.

Furthermore, two other points:

1. As I said in a stream of @icarojobs , I think that all documentation and repositories should be written in pt_BR, to attract the Asaas attention, except the code, because Asaas is a Brazilian bank, then only Brazilian citizens will consume that.

2. There is a PHP package with many downloads, I believe it is the API used for PHP in general when you want to work with Asaas. Maybe it would be interesting for this package to become a wrapper for Laravel consuming this API: https://github.com/codephix/asaas-sdk

Hope this helps. Greetings!

**Comment by wandesnet** [comment]
Hey @devajmeireles, so far I haven't discussed this with @icarojobs, but I completely agree with you. I think it would be more beneficial to include **Laravel** in the name, as this would make the reference clearer to our community.

**Comment by devajmeireles** [comment]
Exactly! Another point, [according to the Laravel Support Policy](https://laravel.com/docs/10.x/releases#support-policy), Laravel 10 is compatible with PHP 8.1 or higher, so it doesn't make sense to have compatibility with Laravel 10, but require PHP 8.2, the correct is PHP 8.1 for Laravel 10 and 8.2 for Laravel 11.

CleanShot 2024-01-12 at 11 28 24

**Review by icarojobs — CHANGES_REQUESTED** [review]
Do the changes about discord...

**Review by icarojobs — APPROVED** [review]
Thank you!

**Comment by icarojobs** [comment]
PR accepted as discussed in discord this morning 😉

**Pull request merged**
